/* Auto-generated by rip_icns2c.py -- do not edit */
#pragma once
#include "rip_icons_data.h"  /* reuse rip_icon_entry_t */

#define RIP_ICN_COUNT 3
extern const rip_icon_entry_t rip_icn_table[RIP_ICN_COUNT];
