/* Auto-generated by rip_icons2c.py — do not edit */
#pragma once
#include <stdint.h>

typedef struct {
    const char    *filename;  /* uppercase, no extension */
    const uint8_t *pixels;    /* 8bpp top-down, palette indices */
    uint16_t       width;
    uint16_t       height;
} rip_icon_entry_t;

#define RIP_ICON_COUNT 95
extern const rip_icon_entry_t rip_icon_table[RIP_ICON_COUNT];
