#!/usr/bin/env python3
"""Execute the pinned driver's pure ellipse generator in an x86 emulator.

Usage: python scripts/dll-affine-fixtures.py C:/RIPtel/RIPSCRIP.DLL --check
Requires unicorn; neither the DLL nor executable code is vendored. The
checked-in fixture contains only input coordinates and point-run hashes.
This proves geometry, not GDI raster/pixel equivalence.
"""
import argparse
import hashlib
import importlib.util
from pathlib import Path
import struct

CASES = [
    [100,100,150,100,100,60,150,100,100,60],  # quarter turn
    [100,100,150,100,100,60,150,100,150,100], # coincident rays: whole ellipse
    [100,100,150,100,100,60,100,100,100,100], # centre rays default to axes
    [100,100,150,100,100,60,149,99,147,90],   # subsegment endpoints
    [100,100,150,100,100,60,147,90,149,99],   # wraps through zero
    [100,100,100,60,150,100,70,120,140,90],  # reversed axes
    [100,100,140,80,110,60,140,80,110,60],   # nonorthogonal axes
    [100,100,100,100,100,100,110,100,100,110], # point degeneracy
    [251,593,314,413,238,244,619,145,553,327], # same segment after truncation
    [100,100,150,100,200,100,150,100,100,120], # collinear axes, start ray misses
    [100,100,100,100,100,150,110,90,90,110],   # one zero radius
    [100,100,200,99,250,98,150,100,100,120],  # integer angle ordering
    [100,100,150,100,200,100,100,120,150,100], # end ray misses
]

def generate(dll):
    from unicorn import Uc, UC_ARCH_X86, UC_MODE_32
    from unicorn.x86_const import UC_X86_REG_ESP, UC_X86_REG_EAX
    spec = importlib.util.spec_from_file_location("pe", Path(__file__).with_name("dll-disasm.py"))
    pe = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(pe)
    data, sections = pe.load(dll)
    if hashlib.md5(data).hexdigest() != "bade8b1f4e467ac7ad4edb2639738d4c":
        raise ValueError("not the audited driver image")
    vm = Uc(UC_ARCH_X86, UC_MODE_32)
    vm.mem_map(pe.IB, 0x100000)
    for s in sections:
        vm.mem_write(pe.IB+s['rva'], data[s['raw']:s['raw']+s['rs']])
    vm.mem_map(0x100000, 0x200000)
    lines = ["/* Generated by scripts/dll-affine-fixtures.py from DLL MD5",
             " * bade8b1f4e467ac7ad4edb2639738d4c, RVA 0x00FA70. */",
             "static const struct { int mode; int16_t xy[10]; int closed, count; uint32_t hash; }",
             "affine_fixtures[] = {"]
    for mode in range(4):
        for xy in CASES:
            args = [0x100000, mode, *xy, 0x110000, 0x120000, 0x120010]
            vm.mem_write(0x2ff000, struct.pack('<'+'I'*len(args), *args))
            vm.reg_write(UC_X86_REG_ESP, 0x2ff000)
            vm.emu_start(pe.IB+0xfa70, 0x100000, count=1000000)
            n = struct.unpack('<I', vm.mem_read(0x120000,4))[0]
            if n > 76:
                raise ValueError(f"invalid point count {n}")
            h = 2166136261
            for (v,) in struct.iter_unpack('<i', vm.mem_read(0x110000,8*n)):
                h = ((h ^ (v & 0xffff)) * 16777619) & 0xffffffff
            closed = vm.reg_read(UC_X86_REG_EAX)
            lines.append(f"    {{{mode}, {{{','.join(map(str,xy))}}}, {closed}, {n}, 0x{h:08x}u}},")
    return '\n'.join(lines + ['};', ''])

def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('dll')
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    path = Path(__file__).resolve().parents[1]/'tests/fixtures/affine_oval.h'
    result = generate(args.dll)
    if args.check:
        if path.read_text() != result:
            raise SystemExit('affine fixture differs from driver output')
        print(f'{4*len(CASES)} affine point runs match the driver oracle')
    else:
        path.write_text(result)

if __name__ == '__main__':
    main()
