#!/usr/bin/env python3
"""dll-marker-glyphs.py -- extract the 36 RIP_PolyMarker glyph outlines.

'|;' RIP_PolyMarker selects one of 36 designs.  The handler at RVA 0x01E4FF
special-cases marker 0 -- it calls the shared ellipse generator at
0x10010160 with a full 0..360 sweep, so marker 0 is a circle -- and passes
every other number to 0x1000F3C6, which indexes a descriptor table:

    mov  eax, [ebp+0xc]              ; marker number
    imul eax, eax, 6                 ; 6 bytes per entry
    lea  esi, [eax + 0x1007ca48]     ; table base

Each descriptor is { uint16 count; int32 (*points)[2]; } and each point is a
pair of int32 in a normalised space of roughly +/-50, which the handler
scales by the command's half-width and half-height and rotates by its skew.

Emits a C table for src/ripscrip.c.  Verify the DLL fingerprint before
trusting the output: 592,896 bytes, MD5 bade8b1f4e467ac7ad4edb2639738d4c.

Usage:
    python scripts/dll-marker-glyphs.py <path>/Ripscrip.dll
"""
import argparse
import hashlib
import struct
import sys
from pathlib import Path

IB = 0x10000000
TABLE_RVA = 0x07CA48
MARKER_COUNT = 36


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dll")
    ap.add_argument("--c", action="store_true", help="emit a C table")
    args = ap.parse_args()

    d = Path(args.dll).read_bytes()
    md5 = hashlib.md5(d).hexdigest()
    if md5 != "bade8b1f4e467ac7ad4edb2639738d4c":
        print("WARNING: unexpected image (md5 %s); addresses may not hold" % md5,
              file=sys.stderr)

    pe = struct.unpack_from("<I", d, 0x3C)[0]
    coff = pe + 4
    nsec = struct.unpack_from("<H", d, coff + 2)[0]
    optsz = struct.unpack_from("<H", d, coff + 16)[0]
    secs = []
    so = coff + 20 + optsz
    for i in range(nsec):
        o = so + i * 40
        vs, va, rs, rp = struct.unpack_from("<IIII", d, o + 8)
        secs.append((va, vs, rp, rs))

    def r2o(r):
        for va, vs, rp, rs in secs:
            if va <= r < va + max(vs, rs):
                return r - va + rp
        return None

    base = r2o(TABLE_RVA)
    glyphs = []
    for n in range(MARKER_COUNT):
        cnt, ptr = struct.unpack_from("<HI", d, base + n * 6)
        pts = []
        if cnt:
            o = r2o(ptr - IB)
            for i in range(cnt):
                x, y = struct.unpack_from("<ii", d, o + i * 8)
                pts.append((x, y))
        glyphs.append(pts)

    if not args.c:
        for n, pts in enumerate(glyphs):
            note = "  (circle -- drawn by the ellipse generator)" if not pts else ""
            print("marker %2d: %2d points%s" % (n, len(pts), note))
            if pts:
                print("     " + " ".join("(%d,%d)" % p for p in pts))
        total = sum(len(g) for g in glyphs)
        print("\n%d glyphs, %d points total" % (MARKER_COUNT, total))
        rng = [v for g in glyphs for p in g for v in p]
        print("coordinate range: %d .. %d" % (min(rng), max(rng)))
        return 0

    # ---- C emission -----------------------------------------------------
    out = []
    out.append("/* Generated by scripts/dll-marker-glyphs.py -- do not edit by hand.")
    out.append(" *")
    out.append(" * The 36 RIP_PolyMarker glyph outlines, extracted from the driver's")
    out.append(" * descriptor table at RVA 0x07ca48.  Coordinates are in a normalised")
    out.append(" * space of +/-50 which the caller scales by the marker's half-width and")
    out.append(" * half-height and rotates by its skew.  Marker 0 has no outline: the")
    out.append(" * driver draws it with the shared ellipse generator, so it is a circle. */")
    flat = []
    offs = []
    for g in glyphs:
        offs.append(len(flat))
        for x, y in g:
            flat.append((x, y))
    out.append("static const int8_t rip_marker_pts[][2] = {")
    for i in range(0, len(flat), 8):
        row = "".join("{%4d,%4d}," % p for p in flat[i:i + 8])
        out.append("    " + row)
    out.append("};")
    out.append("")
    out.append("static const struct { uint16_t off; uint8_t n; } rip_marker_glyph[36] = {")
    for n, g in enumerate(glyphs):
        out.append("    { %4d, %2d },   /* %2d */" % (offs[n], len(g), n))
    out.append("};")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
