#!/usr/bin/env python3
"""dll-argtypes.py -- emit the per-command argument-width table.

Most RIPscrip arguments are a fixed number of MegaNum digits, but two kinds
are not: the driver's dispatch record types them 0xFF (width from '|n'
SET_COORDINATE_SIZE) and 0xFE (width from '|M' SET_COLOR_MODE), and resolves
them at decode time -- see the resolver at RVA 0x039DE0.

RIPlib's handlers read fixed 2-digit fields at fixed offsets, in 262 places.
Rather than rewrite all of them, the parser normalises a command's payload to
2-digit fields before dispatch whenever the negotiated widths are not 2.
This table is what makes that possible.

Only commands that actually contain a 0xFF or 0xFE argument are emitted; a
command whose widths are all literal never needs rewriting.

Usage:
    python scripts/dll-argtypes.py <path>/Ripscrip.dll [--c]
"""
import argparse
import hashlib
import struct
import sys
from pathlib import Path

TABLE_RVA = 0x080820
ENTRY_SIZE = 40
ENTRY_COUNT = 129

# Level is inferred from the handler address band, matching segment 13.
def level_of(slot):
    if slot <= 83:
        return 0
    if slot <= 109:
        return 1
    if slot <= 121:
        return 2
    return 3


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dll")
    ap.add_argument("--c", action="store_true", help="emit a C table")
    args = ap.parse_args()

    d = Path(args.dll).read_bytes()
    md5 = hashlib.md5(d).hexdigest()
    if md5 != "bade8b1f4e467ac7ad4edb2639738d4c":
        print("WARNING: unexpected image (md5 %s)" % md5, file=sys.stderr)

    pe = struct.unpack_from("<I", d, 0x3C)[0]
    coff = pe + 4
    nsec = struct.unpack_from("<H", d, coff + 2)[0]
    optsz = struct.unpack_from("<H", d, coff + 16)[0]
    secs = []
    so = coff + 20 + optsz
    for i in range(nsec):
        o = so + i * 40
        vs, va, rs, rp = struct.unpack_from("<IIII", d, o + 8)
        secs.append((va, vs, rp, rs))

    def r2o(r):
        for va, vs, rp, rs in secs:
            if va <= r < va + max(vs, rs):
                return r - va + rp
        return None

    base = r2o(TABLE_RVA)
    rows = []
    for i in range(ENTRY_COUNT):
        raw = d[base + i * ENTRY_SIZE: base + (i + 1) * ENTRY_SIZE]
        letter = raw[15]
        argc = struct.unpack_from("<i", raw, 16)[0]
        types = []
        for b in raw[20:38]:
            if b == 0:
                break
            types.append(b)
        if not (0x20 <= letter < 0x7F) or argc <= 0 or not types:
            continue
        if 0xFF not in types and 0xFE not in types:
            continue                       # all literal widths: never rewritten
        rows.append((chr(letter), level_of(i), types))

    if not args.c:
        for ch, lvl, types in rows:
            print("  |%s%s  %s" % (lvl or "", ch,
                                   " ".join("%02X" % t for t in types)))
        print("\n%d commands need width normalisation" % len(rows))
        print("max argument count: %d" % max(len(t) for _, _, t in rows))
        return 0

    maxn = max(len(t) for _, _, t in rows)
    print("/* Generated by scripts/dll-argtypes.py -- do not edit by hand.")
    print(" *")
    print(" * Commands containing at least one argument whose width is negotiated")
    print(" * rather than literal: 0xFF takes its width from '|n', 0xFE from '|M'.")
    print(" * Everything else has fixed widths and never needs rewriting, so it is")
    print(" * deliberately absent. */")
    print("#define RIP_ARGTYPE_MAX %d" % maxn)
    print("typedef struct {")
    print("    uint8_t letter;   /* command character            */")
    print("    uint8_t level;    /* 0..3                         */")
    print("    uint8_t n;        /* argument count               */")
    print("    uint8_t t[RIP_ARGTYPE_MAX];")
    print("} rip_argtypes_t;")
    print("")
    print("static const rip_argtypes_t rip_argtypes[] = {")
    for ch, lvl, types in rows:
        pad = types + [0] * (maxn - len(types))
        print("    { '%s', %d, %2d, {%s} }," %
              (ch if ch != "'" and ch != "\\" else "\\" + ch, lvl, len(types),
               ",".join("0x%02X" % t for t in pad)))
    print("};")
    print("#define RIP_ARGTYPES_COUNT %d" % len(rows))
    return 0


if __name__ == "__main__":
    sys.exit(main())
