/* Generated by dll-raster-fixtures.py; driver MD5 bade8b1f4e467ac7ad4edb2639738d4c. */
static const uint32_t image_rop_fixtures[] = {
    0x00cc0020u, 0x00660046u, 0x00ee0086u, 0x008800c6u, 0x00330008u, 0x00cc0020u
};
