/*
 * rip_icons.c — RIPscrip icon loader for A2GSPU card
 *
 * Flash-embedded icons: rip_icons_data.c (generated by rip_icons2c.py)
 * Runtime cache: PSRAM-allocated, keyed by uppercase filename (no ext)
 *
 * Copyright (c) 2026 Brad Hawthorne
 * Licensed under GPL-3.0
 */

#include "rip_icons.h"
#include "rip_icons_data.h"
#include "rip_icns_data.h"
#include <string.h>

/* Session arena — set by rip_icon_set_arena() on each rip_init(). */
#include "riplib_platform.h"
static psram_arena_t *g_arena = NULL;

/* ── Runtime PSRAM cache ─────────────────────────────────────────── */

#define ICON_CACHE_MAX  64  /* max cached runtime icons */
#define ICON_NAME_MAX   12  /* 8.3 filename stem */

typedef struct {
    char     name[ICON_NAME_MAX + 1];
    uint8_t *pixels;
    uint16_t width;
    uint16_t height;
} icon_cache_entry_t;

static icon_cache_entry_t cache[ICON_CACHE_MAX];
static int cache_count = 0;

/* Case-insensitive compare, up to len chars */
static bool name_match(const char *a, int alen, const char *b) {
    int blen = (int)strlen(b);
    if (alen != blen) return false;
    for (int i = 0; i < alen; i++) {
        char ca = a[i], cb = b[i];
        if (ca >= 'a' && ca <= 'z') ca -= 32;
        if (cb >= 'a' && cb <= 'z') cb -= 32;
        if (ca != cb) return false;
    }
    return true;
}

/* ── Arena binding + cache reset ─────────────────────────────────── */

void rip_icon_set_arena(psram_arena_t *arena) {
    g_arena = arena;
    /* Reset the runtime cache: pointers into the old arena are now invalid.
     * Flash-embedded icons (rip_icon_table, rip_icn_table) are unaffected. */
    cache_count = 0;
}

/* ── Flash icon lookup ───────────────────────────────────────────── */

bool rip_icon_lookup(const char *name, int name_len, rip_icon_t *out) {
    /* Strip extension if present */
    for (int i = 0; i < name_len; i++) {
        if (name[i] == '.') { name_len = i; break; }
    }

    /* 1. Check flash-embedded BMP table */
    for (int i = 0; i < RIP_ICON_COUNT; i++) {
        if (name_match(name, name_len, rip_icon_table[i].filename)) {
            out->pixels = rip_icon_table[i].pixels;
            out->width  = rip_icon_table[i].width;
            out->height = rip_icon_table[i].height;
            return true;
        }
    }

    /* 1b. Check flash-embedded ICN table */
    for (int i = 0; i < RIP_ICN_COUNT; i++) {
        if (name_match(name, name_len, rip_icn_table[i].filename)) {
            out->pixels = rip_icn_table[i].pixels;
            out->width  = rip_icn_table[i].width;
            out->height = rip_icn_table[i].height;
            return true;
        }
    }

    /* 2. Check PSRAM runtime cache */
    for (int i = 0; i < cache_count; i++) {
        if (name_match(name, name_len, cache[i].name)) {
            out->pixels = cache[i].pixels;
            out->width  = cache[i].width;
            out->height = cache[i].height;
            return true;
        }
    }

    return false;
}

/* ── BMP parser + PSRAM cache ────────────────────────────────────── */

bool rip_icon_cache_bmp(const char *name, int name_len,
                        const uint8_t *data, int size) {
    if (size < 54 || data[0] != 'B' || data[1] != 'M')
        return false;
    if (cache_count >= ICON_CACHE_MAX)
        return false;

    /* Parse BMP header */
    uint32_t pixel_offset = data[10] | (data[11] << 8) |
                            (data[12] << 16) | (data[13] << 24);
    int32_t width  = (int32_t)(data[18] | (data[19] << 8) |
                               (data[20] << 16) | (data[21] << 24));
    int32_t height = (int32_t)(data[22] | (data[23] << 8) |
                               (data[24] << 16) | (data[25] << 24));
    uint16_t bpp   = data[28] | (data[29] << 8);
    uint32_t comp  = data[30] | (data[31] << 8) |
                     (data[32] << 16) | (data[33] << 24);

    if (comp != 0) return false;          /* uncompressed only */
    if (bpp != 4 && bpp != 8) return false;
    if (width <= 0 || width > 640) return false;

    bool bottom_up = (height > 0);
    if (height < 0) height = -height;
    if (height > 400) return false;

    uint32_t pixel_count = (uint32_t)width * (uint32_t)height;
    if (!g_arena) return false;
    uint8_t *pixels = (uint8_t *)psram_arena_alloc(g_arena, pixel_count);
    if (!pixels) return false;

    /* Row stride (padded to 4 bytes) */
    int row_bytes;
    if (bpp == 4)
        row_bytes = (((int)width + 1) / 2 + 3) & ~3;
    else
        row_bytes = ((int)width + 3) & ~3;

    /* Convert to 8bpp top-down */
    for (int y = 0; y < (int)height; y++) {
        int src_y = bottom_up ? ((int)height - 1 - y) : y;
        int row_off = (int)pixel_offset + src_y * row_bytes;
        int dst_off = y * (int)width;

        for (int x = 0; x < (int)width; x++) {
            if (bpp == 4) {
                int bi = row_off + x / 2;
                if (bi < size)
                    pixels[dst_off + x] = (x & 1) ? (data[bi] & 0x0F) : (data[bi] >> 4);
            } else {
                int bi = row_off + x;
                if (bi < size)
                    pixels[dst_off + x] = data[bi];
            }
        }
    }

    /* Store in cache */
    icon_cache_entry_t *e = &cache[cache_count];
    int nlen = name_len;
    /* Strip extension */
    for (int i = 0; i < nlen; i++) {
        if (name[i] == '.') { nlen = i; break; }
    }
    if (nlen > ICON_NAME_MAX) nlen = ICON_NAME_MAX;
    for (int i = 0; i < nlen; i++) {
        char c = name[i];
        e->name[i] = (c >= 'a' && c <= 'z') ? (c - 32) : c;
    }
    e->name[nlen] = '\0';
    e->pixels = pixels;
    e->width  = (uint16_t)width;
    e->height = (uint16_t)height;
    cache_count++;

    return true;
}

bool rip_icon_cache_pixels(const char *name, int name_len,
                           uint8_t *pixels, uint16_t w, uint16_t h) {
    if (cache_count >= ICON_CACHE_MAX || !pixels)
        return false;

    icon_cache_entry_t *e = &cache[cache_count];
    int nlen = name_len;
    for (int i = 0; i < nlen; i++) {
        if (name[i] == '.') { nlen = i; break; }
    }
    if (nlen > ICON_NAME_MAX) nlen = ICON_NAME_MAX;
    for (int i = 0; i < nlen; i++) {
        char c = name[i];
        e->name[i] = (c >= 'a' && c <= 'z') ? (c - 32) : c;
    }
    e->name[nlen] = '\0';
    e->pixels = pixels;
    e->width  = w;
    e->height = h;
    cache_count++;
    return true;
}

int rip_icon_cache_count(void) {
    return cache_count;
}

/* ── File request queue ──────────────────────────────────────────── */

static char request_queue[RIP_FILE_REQUEST_MAX][RIP_FILE_NAME_MAX + 1];
static int  request_lengths[RIP_FILE_REQUEST_MAX];
static int  request_head = 0;  /* next slot to dequeue */
static int  request_tail = 0;  /* next slot to enqueue */
static int  request_count = 0;

bool rip_icon_request_file(const char *name, int name_len) {
    if (request_count >= RIP_FILE_REQUEST_MAX)
        return false;

    /* Strip extension */
    for (int i = 0; i < name_len; i++) {
        if (name[i] == '.') { name_len = i; break; }
    }
    if (name_len > RIP_FILE_NAME_MAX) name_len = RIP_FILE_NAME_MAX;

    /* Don't queue duplicates */
    for (int i = 0; i < request_count; i++) {
        int idx = (request_head + i) % RIP_FILE_REQUEST_MAX;
        if (name_match(name, name_len, request_queue[idx]))
            return true; /* already queued */
    }

    /* Enqueue — store uppercase */
    char *dst = request_queue[request_tail];
    for (int i = 0; i < name_len; i++) {
        char c = name[i];
        dst[i] = (c >= 'a' && c <= 'z') ? (c - 32) : c;
    }
    dst[name_len] = '\0';
    request_lengths[request_tail] = name_len;
    request_tail = (request_tail + 1) % RIP_FILE_REQUEST_MAX;
    request_count++;
    return true;
}

int rip_icon_pending_requests(void) {
    return request_count;
}

int rip_icon_dequeue_request(char *name_out, int max_len) {
    if (request_count == 0) return 0;

    int len = request_lengths[request_head];
    if (len > max_len) len = max_len;
    memcpy(name_out, request_queue[request_head], len);

    request_head = (request_head + 1) % RIP_FILE_REQUEST_MAX;
    request_count--;
    return len;
}

/* Codex FIX 4: Discard all pending file requests.
 * Called by rip_session_reset() on disconnect so icon requests from
 * the previous BBS session are not carried over to the next connection. */
void rip_icon_clear_requests(void) {
    request_head  = 0;
    request_tail  = 0;
    request_count = 0;
}
